---
- name: Start httpd service
  hosts: 
    - test
    - prod
    - dev
  become: yes  i

  tasks:
    - name: Ensure httpd service is running
      service:
        name: httpd
        state: started

    - name: enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Add httpd service to firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
